language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
cache:
  directories:
    - node_modules
#before_script:
install:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href /ang-ci/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
